export default {
  name: 'amenities',
  title: 'Amenities',
  type: 'document',
  fields: [
    {
      name: 'name',
      title: 'Name',
      type: 'string',
    },
    {
      name: 'amenities',
      title: 'Amenity Types',
      type: 'array',
      of: [{type: 'string'}],
      options: {
        list: [
          {title: 'Gated Community', value: 'Gated Community'},
          {title: 'Kids Area', value: 'Kids Area'},
          {title: 'Kids Club', value: 'Kids Club'},
          {title: 'Retail Area', value: 'Retail Area'},
          {title: 'Grocery Store', value: 'Grocery Store'},
          {title: 'Gymnasium', value: 'Gymnasium'},
          {title: 'Pool', value: 'Pool'},
          {title: 'Helper Room', value: 'Helper Room'},
          {title: 'Maids Room', value: 'Maids Room'},
          {title: 'High-speed Internet', value: 'High-speed Internet'},
          {title: 'Reception Service', value: 'Reception Service'},
          {title: 'Concierge Service', value: 'Concierge Service'},
          {title: 'Steam Room', value: 'Steam Room'},
          {title: 'Spa', value: 'Spa'},
          {title: 'Meeting Room', value: 'Meeting Room'},
          {title: 'Video Security', value: 'Video Security'},
          {title: 'Restaurant', value: 'Restaurant'},
          {title: 'Jacuzzi', value: 'Jacuzzi'},
          {title: 'Sauna', value: 'Sauna'},
          {title: 'Cleaning Service', value: 'Cleaning Service'},
          {title: 'Infinity Pool', value: 'Infinity Pool'},
          {title: 'Overflow Pool', value: 'Overflow Pool'},
          {title: 'Residents Lounge Area', value: 'Residents Lounge Area'},
          {title: 'Valet Parking', value: 'Valet Parking'},
          {title: 'Laundry Service', value: 'Laundry Service'},
          {title: 'Package Room', value: 'Package Room'},
          {title: 'Security Gate', value: 'Security Gate'},
          {title: 'Room Service', value: 'Room Service'},
          {title: 'Smart Home Technology', value: 'Smart Home Technology'},
          {title: 'Yoga Studio', value: 'Yoga Studio'},
          {title: 'Private Storage', value: 'Private Storage'},
          {title: 'Garage', value: 'Garage'},
          {title: 'Doorman', value: 'Doorman'},
          {title: 'Bar', value: 'Bar'},
          {title: 'Common Garden', value: 'Common Garden'},
          {title: 'BBQ Area', value: 'BBQ Area'},
          {title: 'Common Terrace', value: 'Common Terrace'},
        ],
        layout: 'checkbox',
      },
    },
  ],
}
