export default {
  name: 'projects',
  title: 'Projects',
  type: 'document',
  fields: [
    {
      name: 'title',
      title: 'Title',
      type: 'string',
    },
    {
      name: 'location',
      title: 'Location',
      type: 'geopoint',
    },
    {
      name: 'projectPropertyTypes',
      title: 'Project Property Types',
      type: 'array',
      of: [{type: 'string'}],
      options: {
        list: [
          {title: 'Villas', value: 'Villas'},
          {title: 'Townhouses', value: 'Townhouses'},
          {title: 'Apartments', value: 'Apartments'},
        ],
        layout: 'checkbox',
      },
    },
    {
      name: 'unitType',
      title: 'Unit Type',
      type: 'string',
      options: {
        list: [
          {title: '2-3 Bedrooms', value: '2-3 Bedrooms'},
          {title: '2-4 Bedrooms', value: '2-4 Bedrooms'},
          {title: '3-4 Bedrooms', value: '3-4 Bedrooms'},
          {title: '3-5 Bedrooms', value: '3-5 Bedrooms'},
          {title: '5-6 Bedrooms', value: '5-6 Bedrooms'},
          {title: '7+ Bedrooms', value: '7+ Bedrooms'},
        ],
        layout: 'radio',
      },
    },
    {
      name: 'mainProjectImage',
      title: 'Main Project Image',
      type: 'image',
      options: {
        hotspot: true,
      },
    },
    {
      name: 'projectImages',
      title: 'Project Images',
      type: 'array',
      of: [{type: 'developmentImage'}],
    },
    {
      name: 'mainDeveloper',
      title: 'Main Developer',
      type: 'string',
      options: {
        list: [
          {title: 'Emaar Properties', value: 'Emaar Properties'},
          {title: 'Damac Real Estate', value: 'Damac Real Estate'},
          {title: 'Nakheel Properties', value: 'Nakheel Properties'},
          {title: 'Aldar Properties', value: 'Aldar Properties'},
          {title: 'Manazel Real Estate', value: 'Manazel Real Estate'},
          {title: 'EllingTon Properties', value: 'EllingTon Properties'},
          {title: 'Meraas Real Estate', value: 'Meraas Real Estate'},
          {title: 'Meydan Real Estate', value: 'Meydan Real Estate'},
        ],
        layout: 'radio',
      },
    },
    {
      name: 'projectOffPlan',
      title: 'Project Off Plan',
      type: 'object',
      fields: [
        {
          name: 'offplan',
          title: 'Off-Plan',
          type: 'boolean',
        },
        {
          name: 'completionDate',
          title: 'Completion Date',
          type: 'string',
        },
      ],
    },
    {
      name: 'totalPrice',
      title: 'Price',
      type: 'number',
    },
    {
      name: 'squareFootage',
      title: 'Square Footage',
      type: 'number',
    },
    {
      name: 'projectBuiltUpArea',
      title: 'Built-up Area',
      type: 'number',
    },
    {
      name: 'projectType',
      title: 'Type',
      type: 'string',
      options: {
        list: [
          {title: 'Building', value: 'building'},
          {title: 'Piece of Land', value: 'pieceOfLand'},
        ],
        layout: 'radio',
      },
    },
    {
      name: 'numFloors',
      title: 'Number of Floors',
      type: 'number',
      hidden: ({parent}: {parent: {projectType: string}}) => parent.projectType !== 'building',
    },
    {
      name: 'numUnits',
      title: 'Number of Units',
      type: 'number',
      hidden: ({parent}: {parent: {projectType: string}}) => parent.projectType !== 'building',
    },
    {
      name: 'numVillas',
      title: 'Number of Villas/Townhouses',
      type: 'number',
      hidden: ({parent}: {parent: {projectType: string}}) => parent.projectType !== 'pieceOfLand',
    },
    {
      name: 'bedrooms',
      title: 'Bedrooms',
      type: 'string',
      options: {
        list: [
          {title: '2-3', value: '2-3'},
          {title: '2-4', value: '2-4'},
          {title: '3-4', value: '3-4'},
          {title: '3-5', value: '3-5'},
          {title: '5-6', value: '5-6'},
          {title: '7+', value: '7+'},
        ],
        layout: 'radio',
      },
      hidden: ({parent}: {parent: {projectType: string}}) => parent.projectType !== 'pieceOfLand',
    },

    {
      name: 'amenities',
      title: 'Amenity Types',
      type: 'array',
      of: [{type: 'string'}],
      options: {
        list: [
          {title: 'Gated Community', value: 'Gated Community'},
          {title: 'Kids Area', value: 'Kids Area'},
          {title: 'Kids Club', value: 'Kids Club'},
          {title: 'Retail Area', value: 'Retail Area'},
          {title: 'Grocery Store', value: 'Grocery Store'},
          {title: 'Gymnasium', value: 'Gymnasium'},
          {title: 'Pool', value: 'Pool'},
          {title: 'Helper Room', value: 'Helper Room'},
          {title: 'Maids Room', value: 'Maids Room'},
          {title: 'High-speed Internet', value: 'High-speed Internet'},
          {title: 'Reception Service', value: 'Reception Service'},
          {title: 'Concierge Service', value: 'Concierge Service'},
          {title: 'Steam Room', value: 'Steam Room'},
          {title: 'Spa', value: 'Spa'},
          {title: 'Meeting Room', value: 'Meeting Room'},
          {title: 'Video Security', value: 'Video Security'},
          {title: 'Restaurant', value: 'Restaurant'},
          {title: 'Jacuzzi', value: 'Jacuzzi'},
          {title: 'Sauna', value: 'Sauna'},
          {title: 'Cleaning Service', value: 'Cleaning Service'},
          {title: 'Infinity Pool', value: 'Infinity Pool'},
          {title: 'Overflow Pool', value: 'Overflow Pool'},
          {title: 'Residents Lounge Area', value: 'Residents Lounge Area'},
          {title: 'Valet Parking', value: 'Valet Parking'},
          {title: 'Laundry Service', value: 'Laundry Service'},
          {title: 'Package Room', value: 'Package Room'},
          {title: 'Security Gate', value: 'Security Gate'},
          {title: 'Room Service', value: 'Room Service'},
          {title: 'Smart Home Technology', value: 'Smart Home Technology'},
          {title: 'Yoga Studio', value: 'Yoga Studio'},
          {title: 'Private Storage', value: 'Private Storage'},
          {title: 'Garage', value: 'Garage'},
          {title: 'Doorman', value: 'Doorman'},
          {title: 'Bar', value: 'Bar'},
          {title: 'Common Garden', value: 'Common Garden'},
          {title: 'BBQ Area', value: 'BBQ Area'},
          {title: 'Common Terrace', value: 'Common Terrace'},
        ],
        layout: 'checkbox',
      },
    },
    {
      name: 'properties',
      title: 'Properties',
      type: 'array',
      of: [{type: 'reference', to: [{type: 'property'}]}],
    },
    {
      name: 'description',
      title: 'Description',
      type: 'string',
    },
    {
      name: 'slug',
      title: 'Slug',
      type: 'slug',
      options: {
        source: 'title',
        maxLength: 100,
      },
    },
    {
      name: 'id',
      title: 'ID',
      type: 'string',
    },
  ],
}
