export default {
  name: 'propertyAmenitiesType',
  title: 'Property Amenities Type',
  type: 'document',
  fields: [
    {
      name: 'name',
      title: 'Name',
      type: 'string',
    },
    {
      name: 'propertiesAmenities',
      title: 'Property Amenity Types',
      type: 'array',
      of: [{type: 'string'}],
      options: {
        list: [
          {title: 'Balcony', value: 'Balcony'},
          {title: 'Built in Wardrobes', value: 'Built in Wardrobes'},
          {title: 'Cable Ready', value: 'Cable Ready'},
          {title: 'Central Air Conditioning', value: 'Central Air Conditioning'},
          {title: 'Concierge Service', value: 'Concierge Service'},
          {title: 'Covered Parking', value: 'Covered Parking'},
          {title: 'Kitchen Appliances', value: 'Kitchen Appliances'},
          {title: 'Maid Service', value: 'Maid Service'},
          {title: 'Maids Room', value: 'Maids Room'},
          {title: 'Pets Allowed', value: 'Pets Allowed'},
          {title: 'Private Garden', value: 'Private Garden'},
          {title: 'Private Gym', value: 'Private Gym'},
          {title: 'Private Jacuzzi', value: 'Private Jacuzzi'},
          {title: 'Private Pool', value: 'Private Pool'},
          {title: 'Pool', value: 'Pool'},
          {title: 'Sea Water View', value: 'Sea Water View'},
          {title: 'Security', value: 'Security'},
          {title: 'Shared Gym', value: 'Shared Gym'},
          {title: 'Shared Swimming Pool', value: 'Shared Swimming Pool'},
          {title: 'Spa', value: 'Spa'},
          {title: 'Study', value: 'Study'},
          {title: 'View of Landmark', value: 'View of Landmark'},
          {title: 'Walk in Closet', value: 'Walk in Closet'},
          {title: 'Basement', value: 'Basement'},
          {title: 'Basement Parking', value: 'Basement Parking'},
          {title: 'BBQ Area', value: 'BBQ Area'},
          {title: 'Beach Access', value: 'Beach Access'},
          {title: 'Carpets', value: 'Carpets'},
          {title: 'Childrens Play Area', value: 'Childrens Play Area'},
          {title: 'City View', value: 'City View'},
          {title: 'Community View', value: 'Community View'},
          {title: 'Drivers Room', value: 'Drivers Room'},
          {title: 'Fully Fitted Kitchen', value: 'Fully Fitted Kitchen'},
          {title: 'Garden View', value: 'Garden View'},
          {title: 'Gazebo', value: 'Gazebo'},
          {title: 'Golf View', value: 'Golf View'},
          {title: 'Heating', value: 'Heating'},
          {title: 'Indoor Swimming Pool', value: 'Indoor Swimming Pool'},
          {title: 'Maintenance', value: 'Maintenance'},
          {title: 'Marble Floors', value: 'Marble Floors'},
          {title: 'On High Floor', value: 'On High Floor'},
          {title: 'On Low Floor', value: 'On Low Floor'},
          {title: 'On Mid Floor', value: 'On Mid Floor'},
          {title: 'Private Garage', value: 'Private Garage'},
          {title: 'Sauna', value: 'Sauna'},
          {title: 'South Orientation', value: 'South Orientation'},
          {title: 'East Orientation', value: 'East Orientation'},
          {title: 'North Orientation', value: 'North Orientation'},
          {title: 'West Orientation', value: 'West Orientation'},
          {title: 'Fireplace', value: 'Fireplace'},
        ],
        layout: 'checkbox',
      },
    },
  ],
}
